global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot-app-test'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'localhost:8091'
          - 'localhost:8092'
        labels:
          app: 'springboot-app-test'
