server:
  port: 9200

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        reject-policy: abort

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfigurationV2
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hello?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: HikariCP
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 600000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true  # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  redis:
    redisson:
      file: classpath:redisson.yaml

# MybatisPlus 配置
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

xxl:
  job:
    enabled: false
    admin:
      access-token: default_token # 执行器通讯TOKEN
      addresses: http://127.0.0.1:9000/xxl-job-admin
      timeout: 3
    executor:
      app-name: xxl-job-executor
      address: ""
      ip: ""
      port: -1
      log-path: /data/logs/xxl-job/job-handler
      log-retention-days: 30

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# url: host:ip/swagger-ui/index.html
springdoc:
  swagger-ui:
    enabled: true
# url: host:ip/doc.html
knife4j:
  enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点，包括自定义端点
  endpoint:
    health:
      show-details: always # 显示详细的健康检查信息
  prometheus:
    metrics:
      export:
        enabled: true